name: example
description: Mpc Wallet Example.
version: 1.0.0
publish_to: none
environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies:
  two_party_ecdsa:
    path: ../
  decimal:
    git:
      url: https://git.bitkinetic.com/flutter/decimal.git

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
